[workspace]
resolver = "2"
members = ["biver", "biver-configuration", "biver-core", "biver-directories"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
uuid = { version = "1.26.0", features = ["v4", "serde"] }
bs58 = "0.5.1"
chrono = { version = "0.4.45", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.4"
thiserror = "2.0.20"
derive_more = { version = "2.1.1", features = ["is_variant"] }
tracing = "0.1.44"